# osman_hadi/osman_bio.py

from .styles import display_banner, his_face1

def bio(lang='b'):
    his_face1()
    display_banner()
    
    if lang.lower() == 'e':
        print("\n--- EXTENDED BIOGRAPHY & HUMAN RIGHTS ARCHIVE ---")
        print("--------------------------------------------------")
        print("Full Name       : Sharif Osman Bin Hadi")
        print("Common Name     : Osman Hadi")
        print("Year of Birth   : 1993")
        print("Place of Birth  : Shariatpur, Bangladesh")
        print("Identity        : Islamic Scholar, Activist, and Public Speaker")
        print("\nEARLY LIFE & BACKGROUND")
        print("Sharif Osman Bin Hadi was born into a respected family in Shariatpur.")
        print("From his youth, he displayed an exceptional intellectual capacity,")
        print("combining traditional theological studies with a deep understanding")
        print("of global politics and human rights.")
        print("\nINTELLECTUAL IDENTITY")
        print("Osman Hadi was not merely a political figure; he was a scholar who")
        print("believed in the 'Theology of Liberation.' He advocated for the")
        print("oppressed and spoke against the systemic violations of human rights")
        print("by autocratic regimes. His life was a testament to the struggle for")
        print("national dignity and the protection of civil liberties in Bangladesh.")
        print("\nCHARACTERISTICS")
        print("He was widely known for his humbleness, articulate speech, and")
        print("fearless stance against injustice. Even under constant threats,")
        print("he remained committed to the principle of non-violent intellectual")
        print("resistance until the violent attack on his life.")
    
    else:
        print("\n--- বিস্তারিত জীবনী ও মানবাধিকার আর্কাইভ ---")
        print("-------------------------------------------")
        print("পূর্ণ নাম        : শরীফ ওসমান বিন হাদি")
        print("ডাক নাম         : ওসমান হাদি")
        print("জন্ম সাল        : ১৯৯৩")
        print("জন্মস্থান       : শরীয়তপুর, বাংলাদেশ")
        print("পরিচয়           : আলেম, রাজনৈতিক সক্রিয়কর্মী এবং সুবক্তা")
        print("\nপ্রারম্ভিক জীবন ও পটভূমি")
        print("শরীফ ওসমান বিন হাদি শরীয়তপুরের এক সম্ভ্রান্ত পরিবারে জন্মগ্রহণ করেন।")
        print("শৈশব থেকেই তিনি অসাধারণ মেধার স্বাক্ষর রাখেন। প্রথাগত ধর্মীয় শিক্ষার")
        print("পাশাপাশি বিশ্ব রাজনীতি এবং মানবাধিকার বিষয়ে তাঁর গভীর জানাশোনা ছিল।")
        print("\nতাত্ত্বিক ও বুদ্ধিবৃত্তিক পরিচয়")
        print("ওসমান হাদি কেবল একজন রাজনৈতিক ব্যক্তিত্ব ছিলেন না; তিনি ছিলেন একজন")
        print("গবেষক। তিনি মজলুমের অধিকার আদায়ে বিশ্বাসী ছিলেন এবং স্বৈরাচারী")
        print("শাসনের মাধ্যমে ঘটা পদ্ধতিগত মানবাধিকার লঙ্ঘনের বিরুদ্ধে সর্বদা সোচ্চার")
        print("ছিলেন। তাঁর জীবন ছিল বাংলাদেশের জাতীয় মর্যাদা এবং নাগরিক স্বাধীনতা")
        print("রক্ষার সংগ্রামের এক জীবন্ত দলিল।")
        print("\nব্যক্তিত্বের বৈশিষ্ট্য")
        print("তিনি তাঁর বিনয়, প্রাঞ্জল ভাষণ এবং অন্যায়ের বিরুদ্ধে নির্ভীক অবস্থানের")
        print("জন্য সর্বমহলে পরিচিত ছিলেন। ক্রমাগত হুমকির মুখেও তিনি তাঁর অহিংস")
        print("বুদ্ধিবৃত্তিক প্রতিরোধের সিদ্ধান্তে অটল ছিলেন, যতক্ষণ না তাঁর ওপর")
        print("সশস্ত্র ও প্রাণঘাতী হামলা চালানো হয়।")